<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita64d36a44d6d9791f6d1de2c70cfb7a0
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PfhubPortfolio\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PfhubPortfolio\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita64d36a44d6d9791f6d1de2c70cfb7a0::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita64d36a44d6d9791f6d1de2c70cfb7a0::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
